name: bad_habit
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.1.0-285.0.dev <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  ###
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.0
  animated_button: ^0.2.0
  flutter_native_splash: ^2.3.1
  easy_localization: ^3.0.2
  ###
flutter_native_splash:
  image: "lib/assets/icon.png"
  color: "#ffffff"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/translations/
  fonts:
    - family: Rubik
      fonts:
        - asset: lib/assets/fonts/Rubik-Medium.ttf
    - family: Nunito
      fonts:
        - asset: lib/assets/fonts/Nunito-SemiBold.ttf
